version: "3.9"
services:

  sqldb:
    image: mysql
    container_name: sqldb
    ports:
      - 30000:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test_db
      MYSQL_USER: shopping
      MYSQL_PASSWORD: 12345678
    restart: always